[project]
name = "gwe"
description = "triplet knoweldge graph with infered ontology"
authors = [{ name = "John C Ll Stokes", email = "johnclstokes@hotmail.com" }]
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]

dependencies = [
    "pydantic<=2.0.0",
    "litellm",
]